-- 阿尔戈斯计划 · 2026 节展回填(festivals 更新 + festival_films 灌入)
-- 生成于 2026-06-12,可重复执行(幂等)。整段粘贴到 Supabase SQL Editor 运行。
alter table festival_films add column if not exists director text;

insert into festivals (id,name,name_cn,tier,kind,country,city,month_window,edition_2026,lineup_status,official_url,notes,updated_at) values
('cannes','Cannes Film Festival','戛纳国际电影节','S','festival','法国','戛纳','5月中下旬','2026-05-12 ~ 05-23(已闭幕)','已公布','https://www.festival-cannes.com','含市场Marché du Film;第79届金棕榈《Fjord》(蒙吉),片单75部已回填(2026-06-12核实)',now()),
('venice','Venice International Film Festival','威尼斯国际电影节','S','festival','意大利','威尼斯','8月底-9月初','2026-09-02 ~ 09-12(已公布)','未公布','https://www.labiennale.org/en/cinema','第83届,评委会主席Maggie Gyllenhaal;通常7月下旬公布片单',now()),
('berlinale','Berlin International Film Festival','柏林国际电影节','S','festival','德国','柏林','2月中旬','2026-02-12 ~ 02-22(已闭幕)','已公布','https://www.berlinale.de','含市场EFM;第76届金熊《Yellow Letters》(伊尔克·查塔克),主竞赛/视点/特别/全景88部已回填(2026-06-12核实)',now()),
('oscars','Academy Awards','奥斯卡金像奖','S','award','美国','洛杉矶','3月','第98届 2026-03-15(已颁)','已公布','https://www.oscars.org','最佳影片《一战再战》(6奖);《罪人》16提名破纪录;全部长片类别35部已回填(2026-06-12核实);2027届提名通常1月公布',now()),
('toronto','Toronto International Film Festival','多伦多国际电影节','A','festival','加拿大','多伦多','9月上中旬','2026-09-10 ~ 09-20(已公布)','未公布','https://tiff.net','第51届;颁奖季风向标,8月起分批公布片单;TIFF市场09-10~09-16',now()),
('sundance','Sundance Film Festival','圣丹斯电影节','A','festival','美国','帕克城','1月下旬','2026-01-22 ~ 02-01(已闭幕)','已公布','https://festival.sundance.org','独立片大本营;犹他州最后一届,2027起迁科罗拉多博尔德',now()),
('busan','Busan International Film Festival','釜山国际电影节','A','festival','韩国','釜山','10月上旬','2026-10-06 ~ 10-15(已公布)','未公布','https://www.biff.kr','第31届;亚洲最大;含亚洲内容市场ACFM',now()),
('locarno','Locarno Film Festival','洛迦诺电影节','A','festival','瑞士','洛迦诺','8月上旬','2026-08-05 ~ 08-15(已公布)','未公布','https://www.locarnofestival.ch','第79届;作者电影/新导演',now()),
('san-sebastian','San Sebastián Film Festival','圣塞巴斯蒂安电影节','A','festival','西班牙','圣塞巴斯蒂安','9月下旬','2026-09-18 ~ 09-26(已公布)','未公布','https://www.sansebastianfestival.com','第74届;西语世界最高规格',now()),
('rotterdam','International Film Festival Rotterdam','鹿特丹国际电影节','A','festival','荷兰','鹿特丹','1月底-2月初','2026-01-29 ~ 02-08(已闭幕)','已公布','https://iffr.com','第55届;先锋/新人',now()),
('tokyo','Tokyo International Film Festival','东京国际电影节','A','festival','日本','东京','10月底-11月初','2026-10-26 ~ 11-04(已公布)','未公布','https://www.tiff-jp.net','第39届;含市场TIFFCOM(10-28~10-30)',now()),
('shanghai','Shanghai International Film Festival','上海国际电影节','A','festival','中国','上海','6月中旬','2026-06-12 ~ 06-21(进行中)','部分公布','https://www.siff.com','第28届金爵奖;今日开幕,展映延长放映至06-28;闭幕后回填获奖名单',now()),
('karlovy-vary','Karlovy Vary International Film Festival','卡罗维发利电影节','A','festival','捷克','卡罗维发利','7月初','2026-07-03 ~ 07-11(已公布)','未公布','https://www.kviff.com','第60届/建节80周年;中东欧最高规格',now()),
('golden-globes','Golden Globe Awards','金球奖','A','award','美国','洛杉矶','1月上旬','第83届 2026-01-11(已颁)','已公布','https://goldenglobes.com','颁奖季第一站;比弗利希尔顿',now()),
('bafta','BAFTA Film Awards','英国电影学院奖','A','award','英国','伦敦','2月中下旬','第79届 2026-02-22(已颁)','已公布','https://www.bafta.org','皇家节日音乐厅,Alan Cumming主持',now()),
('cesar','César Awards','法国凯撒奖','A','award','法国','巴黎','2月底','第51届 2026-02-26(已颁)','已公布','https://www.academie-cinema.org','法国最高电影奖;巴黎Olympia',now()),
('efa','European Film Awards','欧洲电影奖','A','award','欧洲','轮办','1月中旬(已从12月改期)','第38届 2026-01-17(已颁)','已公布','https://europeanfilmawards.eu','★档期变更:已整体从12月移至次年1月,2026年12月无颁奖礼,第39届预计2027-01;本届柏林世界文化宫',now()),
('golden-horse','Golden Horse Awards','金马奖','A','award','中国台湾','台北','11月下旬','第63届 2026-11-22(已公布)','未公布','https://www.goldenhorse.org.tw','华语最高奖之一;入围10月公布;金马影展11-06~11-22;台北流行音乐中心',now()),
('hkfa','Hong Kong Film Awards','香港电影金像奖','A','award','中国香港','香港','4月中旬','第44届 2026-04-19(已颁)','已公布','https://www.hkfaa.com','香港文化中心,ViuTV直播',now()),
('annecy','Annecy International Animation Film Festival','昂西国际动画电影节','A','festival','法国','昂西','6月中下旬','2026-06-21 ~ 06-27(已公布)','已公布','https://www.annecyfestival.com','第50届;动画最高殿堂;本届因G7峰会特例延后约两周;Mifa市场06-23~06-26',now()),
('tribeca','Tribeca Festival','翠贝卡电影节','B','festival','美国','纽约','6月上中旬','2026-06-03 ~ 06-14(收官中)','已公布','https://www.tribecafilm.com','第25届',now()),
('sxsw','SXSW Film & TV Festival','西南偏南电影节','B','festival','美国','奥斯汀','3月中旬','2026-03-12 ~ 03-18(已闭幕)','已公布','https://www.sxsw.com','类型片/新媒体;本届缩短为7天',now()),
('hkiff','Hong Kong International Film Festival','香港国际电影节','B','festival','中国香港','香港','3月底-4月中','第50届 2026-04-01 ~ 04-12(已闭幕)','已公布','https://www.hkiff.org.hk','金禧届;同期香港影视娱乐博览/FilMart(3月,市场)',now()),
('beijing','Beijing International Film Festival','北京国际电影节','B','festival','中国','北京','4月下旬','第16届 2026-04-16 ~ 04-25(已闭幕)','已公布','https://www.bjiff.com','天坛奖;北京展映至04-26',now()),
('golden-rooster','Golden Rooster Awards','金鸡奖','B','award','中国','厦门','11月中旬','未公布(常规11月)','未公布','','内地最高专业奖;第39届日期官方尚未公布;同年百花奖(第38届)预计8月',now()),
('tallinn','Tallinn Black Nights Film Festival','塔林黑夜电影节','B','festival','爱沙尼亚','塔林','11月','2026-11-06 ~ 11-22(已公布)','未公布','https://poff.ee','FIAPF A类;30周年届,塔尔图设分会场',now()),
('sitges','Sitges Film Festival','锡切斯奇幻电影节','B','festival','西班牙','锡切斯','10月上中旬','2026-10-08 ~ 10-18(已公布)','未公布','https://sitgesfilmfestival.com','第59届;类型片/恐怖奇幻最高规格',now()),
('fantasia','Fantasia International Film Festival','奇幻国际电影节(蒙特利尔)','B','festival','加拿大','蒙特利尔','7月中-8月初','2026-07-16 ~ 08-02(已公布)','未公布','https://fantasiafestival.com','第30届;北美最大类型片节',now()),
('afm','American Film Market','美国电影市场(AFM)','B','market','美国','洛杉矶','11月上旬','2026-11-10 ~ 11-15(已公布)','未公布','https://americanfilmmarket.com','★地点变更:已回归洛杉矶Fairmont Century Plaza(不再拉斯维加斯);纯交易市场,版权采购重点场合',now()),
('filmart','Hong Kong FILMART','香港国际影视展(FilMart)','B','market','中国香港','香港','3月中旬','2026-03-17 ~ 03-20(已闭幕)','已公布','https://hkfilmart.hktdc.com','亚洲最大影视交易市场;香港会展中心',now())
on conflict (id) do update set
  name=excluded.name, name_cn=excluded.name_cn, tier=excluded.tier, kind=excluded.kind,
  country=excluded.country, city=excluded.city, month_window=excluded.month_window,
  edition_2026=excluded.edition_2026, lineup_status=excluded.lineup_status,
  official_url=excluded.official_url, notes=excluded.notes, updated_at=now();

insert into festival_films (festival_id,edition,section,title,orig_title,country,director,prize) values
('cannes',2026,'主竞赛','Amarga Navidad',null,'西班牙','Pedro Almodóvar',null),
('cannes',2026,'主竞赛','A Woman''s Life',null,'法国','Charline Bourgeois-Tacquet',null),
('cannes',2026,'主竞赛','La Bola Negra',null,'西班牙','Javier Calvo & Javier Ambrossi','最佳导演奖(与《Fatherland》并列)'),
('cannes',2026,'主竞赛','Coward',null,'比利时','Lukas Dhont','最佳男演员奖(Emmanuel Macchia & Valentin Campagne)'),
('cannes',2026,'主竞赛','Parallel Tales',null,null,'Asghar Farhadi',null),
('cannes',2026,'主竞赛','Paper Tiger',null,'美国','James Gray',null),
('cannes',2026,'主竞赛','The Dreamed Adventure','Das Geträumte Abenteuer','德国','Valeska Grisebach','评审团奖'),
('cannes',2026,'主竞赛','All of a Sudden','Soudain','法国/日本','Hamaguchi Ryusuke(滨口龙介)','最佳女演员奖(Virginie Efira & Tao Okamoto)'),
('cannes',2026,'主竞赛','The Unknown',null,'法国','Arthur Harari',null),
('cannes',2026,'主竞赛','Another Day',null,'法国','Jeanne Herry',null),
('cannes',2026,'主竞赛','Sheep in the Box',null,'日本','Koreeda Hirokazu(是枝裕和)',null),
('cannes',2026,'主竞赛','Hope',null,'韩国','Na Hong-jin(罗泓轸)',null),
('cannes',2026,'主竞赛','Nagi Notes',null,'日本','Fukada Koji(深田晃司)',null),
('cannes',2026,'主竞赛','Gentle Monster',null,'奥地利','Marie Kreutzer',null),
('cannes',2026,'主竞赛','A Man of His Time','Notre Salut','比利时/法国','Emmanuel Marre','最佳编剧奖'),
('cannes',2026,'主竞赛','Fjord',null,'罗马尼亚','Cristian Mungiu','金棕榈奖'),
('cannes',2026,'主竞赛','The Birthday Party',null,'法国','Léa Mysius',null),
('cannes',2026,'主竞赛','Moulin',null,'匈牙利','László Nemes',null),
('cannes',2026,'主竞赛','Fatherland',null,'波兰','Paweł Pawlikowski','最佳导演奖(与《La Bola Negra》并列)'),
('cannes',2026,'主竞赛','The Man I Love',null,'美国','Ira Sachs',null),
('cannes',2026,'主竞赛','The Beloved','El Ser Querido','西班牙','Rodrigo Sorogoyen',null),
('cannes',2026,'主竞赛','Minotaur','Minotaure',null,'Andrei Zvyagintsev(萨金塞夫)','评审团大奖'),
('cannes',2026,'一种关注','Teenage Sex and Death at Camp Miasma',null,'美国','Jane Schoenbrun',null),
('cannes',2026,'一种关注','Elephants in the Fog',null,'尼泊尔','Abinash Bikram Shah','一种关注评审团奖'),
('cannes',2026,'一种关注','Iron Boy',null,'法国','Louis Clichy','一种关注特别评审团奖'),
('cannes',2026,'一种关注','Ben''Imana',null,'卢旺达','Marie-Clémentine Dusabejambo','金摄影机奖(最佳处女作)'),
('cannes',2026,'一种关注','Congo Boy',null,'刚果(金)','Rafiki Fariala','一种关注最佳男演员(Bradley Fiomona Dembeasset)'),
('cannes',2026,'一种关注','Club Kid',null,'美国','Jordan Firstman',null),
('cannes',2026,'一种关注','A Girl''s Story',null,'法国','Judith Godrèche',null),
('cannes',2026,'一种关注','Uļa',null,'拉脱维亚','Viesturs Kairišs',null),
('cannes',2026,'一种关注','Titanic Ocean',null,'希腊','Konstantina Kotzamani',null),
('cannes',2026,'一种关注','Strawberries','La Más Dulce',null,'Laïla Marrakchi',null),
('cannes',2026,'一种关注','The Meltdown','El Deshielo','智利','Manuela Martelli',null),
('cannes',2026,'一种关注','Forever Your Maternal Animal','Siempre Soy Tu Animal Materno',null,'Valentina Maurel','一种关注最佳女演员(Marina de Tavira等三人)'),
('cannes',2026,'一种关注','Yesterday the Eye Didn''t Sleep',null,null,'Rakan Mayasi',null),
('cannes',2026,'一种关注','I''ll Be Gone in June',null,'德国','Katharina Rivilis',null),
('cannes',2026,'一种关注','Words of Love',null,'法国','Rudi Rosenberg',null),
('cannes',2026,'一种关注','Everytime',null,'奥地利','Sandra Wollner','一种关注大奖'),
('cannes',2026,'一种关注','Victorian Psycho',null,'美国','Zachary Wigon',null),
('cannes',2026,'一种关注','All the Lovers in the Night',null,'日本','Sode Yukiko',null),
('cannes',2026,'一种关注','Ulysse',null,'法国','Laetitia Masson',null),
('cannes',2026,'非竞赛','The Electric Kiss',null,'法国','Pierre Salvadori',null),
('cannes',2026,'非竞赛','La Bataille de Gaulle : L''Âge de Fer',null,'法国','Antonin Baudry',null),
('cannes',2026,'非竞赛','Karma',null,'法国','Guillaume Canet',null),
('cannes',2026,'非竞赛','Diamond',null,'美国','Andy Garcia',null),
('cannes',2026,'非竞赛','Forsaken',null,'法国','Vincent Garenq',null),
('cannes',2026,'非竞赛','Crescendo',null,'法国','Agnès Jaoui',null),
('cannes',2026,'非竞赛','Her Private Hell',null,null,'Nicolas Winding Refn',null),
('cannes',2026,'午夜展映','Full Phil',null,'法国','Quentin Dupieux',null),
('cannes',2026,'午夜展映','Species',null,'法国','Marion Le Corroller',null),
('cannes',2026,'午夜展映','Roma Elastica',null,'法国','Bertrand Mandico',null),
('cannes',2026,'午夜展映','Jim Queen',null,'法国','Marco Nguyen & Nicolas Athané',null),
('cannes',2026,'午夜展映','Colony','Gun-Che(군체)','韩国','Yeon Sang-ho(延尚昊)',null),
('cannes',2026,'戛纳首映','La Troisième Nuit',null,'法国','Daniel Auteuil',null),
('cannes',2026,'戛纳首映','The Match',null,null,'Juan Cabral & Santiago Franco',null),
('cannes',2026,'戛纳首映','Marie Madeleine',null,null,'Géssica Généus',null),
('cannes',2026,'戛纳首映','Aquí',null,'葡萄牙','Tiago Guedes',null),
('cannes',2026,'戛纳首映','Orange-Flavoured Wedding',null,'法国','Christophe Honoré',null),
('cannes',2026,'戛纳首映','The Samurai and the Prisoner','Kokurojo','日本','Kurosawa Kiyoshi(黑泽清)',null),
('cannes',2026,'戛纳首映','The End of It',null,'西班牙','Maria Martínez Bayona',null),
('cannes',2026,'戛纳首映','Think Good',null,'法国','Géraldine Nakache',null),
('cannes',2026,'戛纳首映','Visitation','Heimsuchung','德国','Volker Schlöndorff',null),
('cannes',2026,'戛纳首映','Propeller One-Way Night Coach',null,'美国','John Travolta',null),
('cannes',2026,'特别展映','Rehearsals for a Revolution',null,null,'Pegah Ahangarani',null),
('cannes',2026,'特别展映','Les Matins Merveilleux',null,'法国','Avril Besson',null),
('cannes',2026,'特别展映','L''Affaire Marie-Claire',null,'法国','Lauriane Escaffre & Yvo Muller',null),
('cannes',2026,'特别展映','Avedon',null,'美国','Ron Howard',null),
('cannes',2026,'特别展映','Vesna',null,null,'Rostislav Kirpičenko',null),
('cannes',2026,'特别展映','Ashes',null,'墨西哥','Diego Luna',null),
('cannes',2026,'特别展映','Tangles',null,null,'Leah Nelson',null),
('cannes',2026,'特别展映','Les Survivants du Che',null,'法国','Christophe Dimitri Réveille',null),
('cannes',2026,'特别展映','Le Triangle d''Or',null,'法国','Hélène Rosselet-Ruiz',null),
('cannes',2026,'特别展映','John Lennon : The Last Interview',null,'美国','Steven Soderbergh',null),
('cannes',2026,'特别展映','Groundswell',null,'美国','Josh Tickell & Rebecca Tickell',null),
('cannes',2026,'特别展映','Cantona',null,'英国','David Tryhorn & Ben Nicholas',null),
('berlinale',2026,'主竞赛','At the Sea',null,'美国/匈牙利','Kornél Mundruczó',null),
('berlinale',2026,'主竞赛','Dao',null,'法国/几内亚比绍/塞内加尔','Alain Gomis',null),
('berlinale',2026,'主竞赛','Dust',null,'比利时/希腊/波兰/英国','Anke Blondé',null),
('berlinale',2026,'主竞赛','Everybody Digs Bill Evans',null,'爱尔兰/英国','Grant Gee','银熊奖最佳导演(Grant Gee)'),
('berlinale',2026,'主竞赛','Home Stories','Etwas ganz Besonderes','德国','Eva Trobisch',null),
('berlinale',2026,'主竞赛','In a Whisper','À voix basse','法国/突尼斯','Leyla Bouzid',null),
('berlinale',2026,'主竞赛','Josephine',null,'美国','Beth de Araújo',null),
('berlinale',2026,'主竞赛','The Loneliest Man in Town',null,'奥地利','Tizza Covi, Rainer Frimmel',null),
('berlinale',2026,'主竞赛','Flies','Moscas','墨西哥','Fernando Eimbcke','柏林晨报读者奖'),
('berlinale',2026,'主竞赛','My Wife Cries','Meine Frau weint','德国/法国','Angela Schanelec',null),
('berlinale',2026,'主竞赛','A New Dawn','花緑青が明ける日に','法国/日本','Yoshitoshi Shinomiya',null),
('berlinale',2026,'主竞赛','Nightborn','Yön Lapsi','芬兰/法国/立陶宛/英国','Hanna Bergholm',null),
('berlinale',2026,'主竞赛','Nina Roza',null,'比利时/保加利亚/加拿大/意大利','Geneviève Dulude-De Celles','银熊奖最佳剧本'),
('berlinale',2026,'主竞赛','Queen at Sea',null,'英国/美国','Lance Hammer','银熊奖评审团奖;银熊奖最佳配角(Anna Calder-Marshall、Tom Courtenay)'),
('berlinale',2026,'主竞赛','Rose',null,'奥地利/德国','Markus Schleinzer','银熊奖最佳主演(Sandra Hüller)'),
('berlinale',2026,'主竞赛','Rosebush Pruning',null,'德国/意大利/西班牙/英国','Karim Aïnouz',null),
('berlinale',2026,'主竞赛','Soumsoum, the Night of the Stars','Soumsoum, la nuit des astres','乍得/法国','Mahamat-Saleh Haroun',null),
('berlinale',2026,'主竞赛','Salvation','Kurtuluş','法国/希腊/荷兰/沙特阿拉伯/瑞典/土耳其','Emin Alper','银熊奖评审团大奖'),
('berlinale',2026,'主竞赛','Yellow Letters','Gelbe Briefe','德国/法国/土耳其','İlker Çatak','金熊奖最佳影片'),
('berlinale',2026,'主竞赛','We Are All Strangers','我们不是陌生人','新加坡','Anthony Chen(陈哲艺)',null),
('berlinale',2026,'主竞赛','Wolfram',null,'澳大利亚','Warwick Thornton',null),
('berlinale',2026,'主竞赛','Yo (Love Is a Rebellious Bird)',null,'美国','Anna Fitch, Banker White','银熊奖杰出艺术贡献奖'),
('berlinale',2026,'视点','17',null,'北马其顿/塞尔维亚/斯洛文尼亚','Kosara Mitić',null),
('berlinale',2026,'视点','Animol',null,'英国','Ashley Walters',null),
('berlinale',2026,'视点','A Prayer for the Dying',null,'挪威/希腊/英国/瑞典','Dara Van Dusen',null),
('berlinale',2026,'视点','Chronicles from the Siege','وقائع زمن الحصار','阿尔及利亚/法国/巴勒斯坦','Abdallah Al-Khatib','GWFF最佳处女作奖'),
('berlinale',2026,'视点','Filipiñana',null,'新加坡/英国/菲律宾/法国/荷兰','Rafael Manuel',null),
('berlinale',2026,'视点','Forest High','Forêt Ivre','比利时/法国','Manon Coubia','GWFF最佳处女作奖特别提及'),
('berlinale',2026,'视点','Light Pillar','寒夜灯柱','中国','Zao Xu',null),
('berlinale',2026,'视点','Our Secret','Nosso Segredo','巴西/葡萄牙','Grace Passô',null),
('berlinale',2026,'视点','The Red Hangar','Hangar rojo','智利/阿根廷/意大利','Juan Pablo Sallato',null),
('berlinale',2026,'视点','The River Train','El Tren Fluvial','阿根廷','Lorenzo Ferro, Lucas A. Vignale',null),
('berlinale',2026,'视点','Take Me Home',null,'美国','Liz Sargent',null),
('berlinale',2026,'视点','Trial of Hein','Der Heimatlose','德国','Kai Stänicke','泰迪熊奖评审团奖'),
('berlinale',2026,'视点','Truly Naked',null,'荷兰/比利时/法国','Muriel d''Ansembourg',null),
('berlinale',2026,'视点','Where To?','לאן','以色列/德国','Assaf Machnes',null),
('berlinale',2026,'柏林特别','The Blood Countess','Die Blutgräfin','奥地利/卢森堡/德国','Ulrike Ottinger',null),
('berlinale',2026,'柏林特别','Good Luck, Have Fun, Don''t Die',null,'美国/德国/南非','Gore Verbinski',null),
('berlinale',2026,'柏林特别','Heysel 85',null,'比利时/罗马尼亚/荷兰/德国','Teodora Ana Mihai',null),
('berlinale',2026,'柏林特别','No Good Men','Kabul Jan','德国/法国/挪威/丹麦/阿富汗','Shahrbanoo Sadat',null),
('berlinale',2026,'柏林特别','The Only Living Pickpocket in New York',null,'美国','Noah Segan',null),
('berlinale',2026,'柏林特别','The Testament of Ann Lee',null,'英国/美国','Mona Fastvold',null),
('berlinale',2026,'柏林特别','The Weight',null,'美国','Padraic McKinley',null),
('berlinale',2026,'柏林特别','The Ballad of Judas Priest',null,'美国','Sam Dunn, Tom Morello',null),
('berlinale',2026,'柏林特别','Saccharine',null,'澳大利亚','Natalie Erika James',null),
('berlinale',2026,'柏林特别','Sleep No More','Monster Pabrik Rambut','印度尼西亚/新加坡/日本/德国/法国','Edwin',null),
('berlinale',2026,'柏林特别','A Child of My Own','Un hijo propio','墨西哥','Maite Alberdi',null),
('berlinale',2026,'柏林特别','Tutu',null,'英国','Sam Pollard','柏林纪录片奖特别提及'),
('berlinale',2026,'柏林特别','Wax & Gold',null,'奥地利','Ruth Beckermann',null),
('berlinale',2026,'柏林特别','Who Killed Alex Odeh?',null,'美国','Jason Osder, William Lafi Youmans',null),
('berlinale',2026,'全景','Allegro Pastell',null,'德国','Anna Roller',null),
('berlinale',2026,'全景','Árru',null,'挪威/瑞典/芬兰','Elle Sofe Sara',null),
('berlinale',2026,'全景','The Day She Returns','그녀가 돌아온 날','韩国','Hong Sang-soo(洪常秀)',null),
('berlinale',2026,'全景','The Education of Jane Cumming',null,'德国/瑞士/英国','Sophie Heldman',null),
('berlinale',2026,'全景','Enjoy Your Stay',null,'瑞士/法国/菲律宾','Dominik Locher, Honeylyn Joy Alipio',null),
('berlinale',2026,'全景','Four Minus Three','Vier minus drei','奥地利/德国','Adrian Goiginger','全景观众奖剧情片第二名'),
('berlinale',2026,'全景','The Garden We Dreamed','El jardín que soñamos','墨西哥','Joaquín del Paso',null),
('berlinale',2026,'全景','If I Were Alive','Se Eu Fosse Vivo... Vivia','巴西','André Novais Oliveira',null),
('berlinale',2026,'全景','Isabel',null,'巴西/法国','Gabe Klinger',null),
('berlinale',2026,'全景','I Understand Your Displeasure','Ich verstehe Ihren Unmut','德国','Kilian Armando Friedrich',null),
('berlinale',2026,'全景','Iván & Hadoum',null,'西班牙/德国/比利时','Ian de la Rosa','泰迪熊奖最佳长片'),
('berlinale',2026,'全景','Lady',null,'英国','Olive Nwosu',null),
('berlinale',2026,'全景','Lali',null,'巴基斯坦','Sarmad Khoosat',null),
('berlinale',2026,'全景','London',null,'奥地利','Sebastian Brameshuber',null),
('berlinale',2026,'全景','The Moment',null,'美国','Aidan Zamiri',null),
('berlinale',2026,'全景','Mouse',null,null,'Kelly O''Sullivan, Alex Thompson','全景观众奖剧情片第三名'),
('berlinale',2026,'全景','Narciso',null,'巴拉圭/德国/乌拉圭/巴西/葡萄牙/西班牙/法国','Marcelo Martinessi',null),
('berlinale',2026,'全景','Numb','しびれ','日本','Takuya Uchiyama',null),
('berlinale',2026,'全景','Only Rebels Win','Seuls les rebelles','法国/黎巴嫩/卡塔尔','Danielle Arbid',null),
('berlinale',2026,'全景','Paradise',null,'加拿大/法国/加纳','Jérémy Comte',null),
('berlinale',2026,'全景','Prosecution','Staatsschutz','德国','Faraz Shariat','全景观众奖剧情片第一名'),
('berlinale',2026,'全景','Raging','Rumaragasa','菲律宾','Ryan Machado',null),
('berlinale',2026,'全景','Roya',null,'伊朗/德国/卢森堡/捷克','Mahnaz Mohammadi',null),
('berlinale',2026,'全景','Safe Exit','خروج آمن','埃及/利比亚/突尼斯/卡塔尔/德国','Mohammed Hammad',null),
('berlinale',2026,'全景','Shanghai Daughter','上海女儿','中国','Agnis Shen Zhongmin',null),
('berlinale',2026,'全景','Around Paradise','Im Umkreis des Paradieses','德国','Yulia Lokshina',null),
('berlinale',2026,'全景','A Russian Winter','Un hiver russe','法国','Patric Chiha',null),
('berlinale',2026,'全景','Bucks Harbor',null,'美国','Pete Muller','全景观众奖纪录片第三名'),
('berlinale',2026,'全景','Douglas Gordon by Douglas Gordon',null,'英国/法国','Finlay Pretsell',null),
('berlinale',2026,'全景','Enough is Enough','Trop c''est trop','法国/刚果(金)','Elisé Sawasawa',null),
('berlinale',2026,'全景','The Hidden Face of the Earth','La Face cachée de la Terre','法国','Arnaud Alain',null),
('berlinale',2026,'全景','Jaripeo',null,'墨西哥/美国/法国','Efraín Mojica, Rebecca Zweig',null),
('berlinale',2026,'全景','The Other Side of the Sun','الجانب الآخر من الشمس','比利时/法国/沙特阿拉伯','Tawfik Sabouni','全景观众奖纪录片第二名'),
('berlinale',2026,'全景','Siri Hustvedt – Dance Around the Self',null,'德国/瑞士','Sabine Lidl',null),
('berlinale',2026,'全景','Traces','Сліди','乌克兰/波兰','Alisa Kovalenko, Marysia Nikitiuk','全景观众奖纪录片第一名'),
('berlinale',2026,'全景','Tristan Forever',null,'瑞士','Tobias Nölle, Loran Bonnardot',null),
('berlinale',2026,'全景','Two Mountains Weighing Down My Chest','东山飘雨西山晴','德国/荷兰','Viv Li',null),
('oscars',2026,'获奖','One Battle After Another',null,'美国','Paul Thomas Anderson','获奖6项:最佳影片/最佳导演/最佳男配角/最佳改编剧本/最佳剪辑/最佳选角;提名:最佳影片/最佳导演/最佳男主角/最佳男配角×2/最佳女配角/最佳改编剧本/最佳摄影/最佳剪辑/最佳配乐/最佳音响/最佳美术/最佳选角'),
('oscars',2026,'获奖','Sinners',null,'美国','Ryan Coogler','获奖4项:最佳男主角/最佳原创剧本/最佳摄影/最佳配乐;提名:最佳影片/最佳导演/最佳男主角/最佳男配角/最佳女配角/最佳原创剧本/最佳摄影/最佳剪辑/最佳配乐/最佳原创歌曲/最佳音响/最佳美术/最佳服装/最佳化妆与发型/最佳视觉效果/最佳选角'),
('oscars',2026,'获奖','Frankenstein',null,'美国','Guillermo del Toro','获奖3项:最佳美术/最佳服装/最佳化妆与发型;提名:最佳影片/最佳男配角/最佳改编剧本/最佳摄影/最佳配乐/最佳音响/最佳美术/最佳服装/最佳化妆与发型'),
('oscars',2026,'提名','Marty Supreme',null,'美国','Josh Safdie','提名:最佳影片/最佳导演/最佳男主角/最佳原创剧本/最佳摄影/最佳剪辑/最佳美术/最佳服装/最佳选角'),
('oscars',2026,'获奖','Sentimental Value','Affeksjonsverdi','挪威','Joachim Trier','获奖1项:最佳国际影片;提名:最佳影片/最佳导演/最佳女主角/最佳男配角/最佳女配角×2/最佳原创剧本/最佳剪辑/最佳国际影片'),
('oscars',2026,'获奖','Hamnet',null,'英国/美国','Chloé Zhao','获奖1项:最佳女主角;提名:最佳影片/最佳导演/最佳女主角/最佳改编剧本/最佳配乐/最佳美术/最佳服装/最佳选角'),
('oscars',2026,'提名','Bugonia',null,'美国','Yorgos Lanthimos','提名:最佳影片/最佳女主角/最佳改编剧本/最佳配乐'),
('oscars',2026,'获奖','F1',null,'美国','Joseph Kosinski','获奖1项:最佳音响;提名:最佳影片/最佳剪辑/最佳音响/最佳视觉效果'),
('oscars',2026,'提名','The Secret Agent','O Agente Secreto','巴西','Kleber Mendonça Filho','提名:最佳影片/最佳男主角/最佳国际影片/最佳选角'),
('oscars',2026,'提名','Train Dreams',null,'美国','Clint Bentley','提名:最佳影片/最佳改编剧本/最佳摄影/最佳原创歌曲'),
('oscars',2026,'获奖','Avatar: Fire and Ash',null,'美国','James Cameron','获奖1项:最佳视觉效果;提名:最佳服装/最佳视觉效果'),
('oscars',2026,'提名','Blue Moon',null,'美国','Richard Linklater','提名:最佳男主角/最佳原创剧本'),
('oscars',2026,'提名','It Was Just an Accident','یک تصادف ساده','法国/伊朗','Jafar Panahi','提名:最佳原创剧本/最佳国际影片'),
('oscars',2026,'获奖','KPop Demon Hunters',null,'美国','Maggie Kang, Chris Appelhans','获奖2项:最佳动画长片/最佳原创歌曲;提名:最佳动画长片/最佳原创歌曲'),
('oscars',2026,'提名','Sirât',null,'西班牙','Oliver Laxe','提名:最佳国际影片/最佳音响'),
('oscars',2026,'获奖','Weapons',null,'美国','Zach Cregger','获奖1项:最佳女配角;提名:最佳女配角'),
('oscars',2026,'提名','If I Had Legs I''d Kick You',null,'美国','Mary Bronstein','提名:最佳女主角'),
('oscars',2026,'提名','Song Sung Blue',null,'美国','Craig Brewer','提名:最佳女主角'),
('oscars',2026,'提名','The Voice of Hind Rajab','صوت هند رجب','突尼斯','Kaouther Ben Hania','提名:最佳国际影片'),
('oscars',2026,'提名','Arco',null,'法国','Ugo Bienvenu','提名:最佳动画长片'),
('oscars',2026,'提名','Elio',null,'美国','Madeline Sharafian, Domee Shi, Adrian Molina','提名:最佳动画长片'),
('oscars',2026,'提名','Little Amélie or the Character of Rain','Amélie et la métaphysique des tubes','法国','Maïlys Vallade, Liane-Cho Han','提名:最佳动画长片'),
('oscars',2026,'提名','Zootopia 2',null,'美国','Jared Bush, Byron Howard','提名:最佳动画长片'),
('oscars',2026,'获奖','Mr. Nobody Against Putin',null,'丹麦/捷克','David Borenstein, Pavel Talankin','获奖1项:最佳纪录长片;提名:最佳纪录长片'),
('oscars',2026,'提名','The Alabama Solution',null,'美国','Andrew Jarecki, Charlotte Kaufman','提名:最佳纪录长片'),
('oscars',2026,'提名','Come See Me in the Good Light',null,'美国','Ryan White','提名:最佳纪录长片'),
('oscars',2026,'提名','Cutting Through Rocks',null,'伊朗','Sara Khaki, Mohammadreza Eyni','提名:最佳纪录长片'),
('oscars',2026,'提名','The Perfect Neighbor',null,'美国','Geeta Gandbhir','提名:最佳纪录长片'),
('oscars',2026,'提名','Kokuho','国宝','日本','Lee Sang-il','提名:最佳化妆与发型'),
('oscars',2026,'提名','The Smashing Machine',null,'美国','Benny Safdie','提名:最佳化妆与发型'),
('oscars',2026,'提名','The Ugly Stepsister','Den stygge stesøsteren','挪威','Emilie Blichfeldt','提名:最佳化妆与发型'),
('oscars',2026,'提名','Jurassic World Rebirth',null,'美国','Gareth Edwards','提名:最佳视觉效果'),
('oscars',2026,'提名','The Lost Bus',null,'美国','Paul Greengrass','提名:最佳视觉效果'),
('oscars',2026,'提名','Diane Warren: Relentless',null,'美国','Bess Kargman','提名:最佳原创歌曲'),
('oscars',2026,'提名','Viva Verdi!',null,null,null,'提名:最佳原创歌曲')
on conflict (festival_id,edition,title) do update set
  section=excluded.section, orig_title=excluded.orig_title, country=excluded.country,
  director=excluded.director, prize=excluded.prize;