-- 阿尔戈斯计划 · 2026 节展片单回填(卡罗维发利/上影节金爵/翠贝卡/昂西/Fantasia)
-- 共 117 行,幂等 upsert(冲突键 festival_id+edition+title)。在 Supabase SQL Editor 执行。
insert into festival_films (festival_id,edition,section,title,orig_title,country,director,prize,douban_sid,douban_url) values
('karlovy-vary', 2026, '水晶地球仪主竞赛', '3 Weeks After', NULL, '塞尔维亚/保加利亚', 'Miroslav Terzić', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'Black Money for White Nights', NULL, '保加利亚/希腊', 'Kristina Grozeva, Petar Valchanov', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'Chica Checa', NULL, '捷克/法国/斯洛伐克', 'Šimon Holý', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'Five Years, Four Months', NULL, '哥伦比亚/美国', 'Esteban Hoyos García, Juan Miguel Gelacio Ramírez', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'Behind the Rain', NULL, '智利', 'Valeria Sarmiento', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'The Guest', NULL, '丹麦', 'Mads Mengel', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'A Happy Family', NULL, '瑞士', 'Jan-Eric Mack', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'Hijamat', NULL, '德国', 'Nader Saeivar', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'The Lion at My Back', NULL, '塞浦路斯/卢森堡/希腊', 'Tonia Mishiali', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'Pipes', NULL, '黎巴嫩', 'Karim Kassem', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'Only Beautiful Things to Look At', NULL, '斯洛伐克/捷克/匈牙利', 'Ivan Ostrochovský', NULL, NULL, NULL),
('karlovy-vary', 2026, '水晶地球仪主竞赛', 'Fruit Gathering', NULL, '缅甸/法国/捷克', 'Aung Phyoe', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', '33 Steps', NULL, '斯洛伐克/捷克', 'Anna Domček, Šimon Domček', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'Truck Driver', NULL, '西班牙/阿根廷', 'Francisco Marise', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'Against Nature', NULL, '墨西哥', 'Axel Bertha', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'A Whole Person Almost', NULL, '希腊/保加利亚/德国/塞浦路斯/罗马尼亚', 'Efthimis Kosemund-Sanidis', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'Homo Sive Natura', NULL, '意大利', 'Giovanni C. Lorusso', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'The Ink-Stained Hand and the Missing Thumb', NULL, '印度', 'Yashasvi Juyal', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'My Friend the Porn Star', NULL, '奥地利', 'Rosa Friedrich', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'Lover, Not a Fighter', NULL, '斯洛伐克', 'Martina Buchelová', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'Paris Paris', NULL, '比利时', 'Isabelle Tollenaere', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'Rain Catcher', NULL, '意大利/英国', 'Michele Fiascaris', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'Incinerator', NULL, '日本', 'Shuntaro Uchida', NULL, NULL, NULL),
('karlovy-vary', 2026, 'Proxima竞赛', 'Petty Thieves', NULL, '克罗地亚/德国/法国', 'Mate Ugrin', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'Atlantic Rhapsody', '阿特兰蒂克狂想曲', '中国大陆', '钟开锋', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'Halima', NULL, '摩洛哥', 'Yassine Idrissi', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'Iluminada', NULL, '比利时', 'Nicolás Rincón Gille', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'Luiza''s Desert', NULL, '巴西/英国', 'Allan Minas', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'My Own Last Supper', NULL, '印度尼西亚', 'Ismail Basbeth', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'Night of Blindness', NULL, '土耳其/德国', 'Reis Çelik', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'Sea Sons', NULL, '俄罗斯', 'Daniil Melkurov', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'Secret in the Box', NULL, '中国大陆/中国香港', '谭广源', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'Superbuhei', NULL, '德国', 'Joseph Brandl', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'The Great Skull', NULL, '中国大陆', '刘晓阳', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'The Miserable Mother', NULL, '德国/法国', 'Susanne Heinrich', NULL, NULL, NULL),
('shanghai', 2026, '金爵奖主竞赛', 'The Parking Spot', NULL, '加拿大', 'Louis Godbout', NULL, NULL, NULL),
('tribeca', 2026, '美国剧情竞赛', 'Cotton Fever', NULL, '美国', 'Daniel Blake Schwartz', '最佳美国剧情片(创始人奖);最佳摄影(美国剧情)', NULL, NULL),
('tribeca', 2026, '美国剧情竞赛', 'Here I''m Alive', NULL, '美国', 'Joshua Z Weinstein', '评审团特别提及(美国剧情)', NULL, NULL),
('tribeca', 2026, '美国剧情竞赛', 'Summer of Three', NULL, '波多黎各', 'Carlitos Ruiz-Ruiz', '最佳表演+最佳剧本(美国剧情)', NULL, NULL),
('tribeca', 2026, '国际剧情竞赛', 'Labrador – Autopsy of Silence', NULL, '加拿大', 'Rodrigue Jean', '最佳国际剧情片;最佳表演;最佳摄影', NULL, NULL),
('tribeca', 2026, '国际剧情竞赛', 'Funk', NULL, '巴西', '—', '最佳表演特别提及(国际剧情,Duda Santos & Mc Nem)', NULL, NULL),
('tribeca', 2026, '国际剧情竞赛', 'Zejtune', NULL, '马耳他/德国/卡塔尔', 'Alex Camilleri', '最佳剧本(国际剧情)', NULL, NULL),
('tribeca', 2026, '纪录片竞赛', 'Jail Time Records', NULL, '喀麦隆/美国', 'Dione Roach, Steve Happi', '最佳纪录片;最佳新人纪录片导演(Maysles奖);最佳摄影(纪录)', NULL, NULL),
('tribeca', 2026, '纪录片竞赛', 'Time Warp', NULL, '美国', 'Allison Berg', '评审团特别提及(纪录片)', NULL, NULL),
('tribeca', 2026, '纪录片竞赛', 'Siege of Paradise', NULL, '爱尔兰/瑞士', 'Lukas Gut', '摄影特别提及(纪录片)', NULL, NULL),
('tribeca', 2026, '纪录片竞赛', 'Jean-Michel', NULL, '美国', '—', '最佳剪辑(纪录片)', NULL, NULL),
('tribeca', 2026, '纪录片竞赛', 'American Zoo', NULL, '英国', '—', '剪辑特别提及(纪录片)', NULL, NULL),
('tribeca', 2026, 'Viewpoints单元', 'Crocodile', NULL, '尼日利亚/新西兰', 'The Critics, Pietra Brettkelly', 'Viewpoints单元奖', NULL, NULL),
('tribeca', 2026, 'Viewpoints单元', 'One Woman One Bra', NULL, '肯尼亚/尼日利亚', 'Sarah Karei', 'Viewpoints特别提及', NULL, NULL),
('tribeca', 2026, '竞赛', 'Memorizu', NULL, '日本', 'Miiku Sakanishi', '最佳新人剧情导演', NULL, NULL),
('tribeca', 2026, '竞赛', 'The Tropic Sun and His Eyes', NULL, '海地', 'Elisee Junior St. Preux', '新人剧情导演特别提及', NULL, NULL),
('tribeca', 2026, '纪录片竞赛', 'Harvest', NULL, '美国', 'Natalie Baszile, Hyacinth Parker', 'Maysles奖特别提及', NULL, NULL),
('tribeca', 2026, '竞赛', 'Skateboarding Is Not for Girls', NULL, '北马其顿/比利时/斯洛文尼亚/克罗地亚', 'Dina Duma', 'Nora Ephron奖', NULL, NULL),
('annecy', 2026, '长片主竞赛', 'Viva Carmen!', NULL, '法国', 'Sébastien Laudenbach', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'Iron Boy', NULL, '法国/比利时', 'Louis Clichy', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'Decorado', NULL, '西班牙/葡萄牙', 'Alberto Vázquez', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'The Sunrise File', NULL, '法国/卢森堡', 'Rupert Wyatt, Émilie Phuong', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'In Waves', NULL, '法国/比利时', 'Phuong Mai Nguyen', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'Lucy Lost', NULL, '法国', 'Olivier Clert', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'Nobody', NULL, '中国大陆', '水尤', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'Tana', NULL, '中国大陆', 'Ji Zhao, Ke Er Zhu', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'Tangles', NULL, '加拿大/美国', 'Leah Nelson', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'The Violinist', NULL, '新加坡/西班牙/意大利', 'Ervin Han, Raúl García', NULL, NULL, NULL),
('annecy', 2026, '长片主竞赛', 'We Are Aliens', NULL, '日本/法国', 'Kohei Kadowaki', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', '58th', NULL, '菲律宾', 'Carl Joseph Papa', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'A New Dawn', NULL, '日本/法国', 'Yoshitoshi Shinomiya', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'Blaise', NULL, '法国', 'Dimitri Planchon, Jean-Paul Guigue', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'O filho da puta', NULL, '巴西', 'Érica Maradona, Otto Guerra, Tania Anaya, Sávio Leite', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'Muyi and the Handsome General', NULL, '法国', 'Julien Chheng', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'Pelelui: Guernica of Paradise', NULL, '日本', 'Goro Kuji', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'Spacetime Chronicles', NULL, '意大利', 'Stefano Bertelli', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'The Obsessed', NULL, '日本', 'Wataru Takahashi', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'The Orbit of Minor Satellites', NULL, '美国/日本', 'Christopher Sullivan', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'Winnipeg, Seeds of Hope', NULL, '西班牙/智利/阿根廷', 'Beñat Beitia, Elio Quiroga', NULL, NULL, NULL),
('annecy', 2026, 'Contrechamp竞赛', 'Welcome to Dolly''s House', NULL, '中国台湾', 'Seven Ych, Rady Fu, Tree Muta', NULL, NULL, NULL),
('annecy', 2026, '开幕片(非竞赛)', 'Minions & Monsters', NULL, '美国', 'Pierre Coffin', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'The Last Temptation of Becky', NULL, '美国', 'Jenn Wexler', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'No Rest for the Wicked', NULL, NULL, 'Kasper Kalle', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Ferine', NULL, '意大利', 'Andrea Corsini', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'You Are the Film', NULL, '日本', 'Makoto Ueda', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'The Eyes', NULL, '韩国', 'Yeom Ji-oh', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Sour Minnows', NULL, '美国', 'Harrison Atkins', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Kung Fu', NULL, '中国台湾', '九把刀', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Home Bodies', NULL, '加拿大/美国', 'Casey Walker', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Captured!', NULL, '日本', 'Koichi', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Tight Lettuce', NULL, '加拿大', 'Harrison Houde', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Unholy Night', NULL, '美国', 'Michael Gabriele', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Break Free', NULL, '日本', 'Yu Nakamoto', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Hot Spot', NULL, '波兰', 'Agnieszka Smoczyńska', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Anymart', NULL, '日本', 'Yusuke Iwasaki', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Sleep No More', NULL, '印度尼西亚', 'Edwin', NULL, NULL, NULL),
('fantasia', 2026, '首批片单', 'Suzuki=Bakudan', NULL, '日本', 'Akira Nagai', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'God Skin', NULL, '泰国', 'Paween Purijitpanya', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Los Vampires', NULL, '美国', 'Craig Mitchell', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Tokyo Burst: Crime City', NULL, '日本', 'Eiji Uchida', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Corpus', NULL, '美国', 'Corrin Evans', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Someone''s Daughter', NULL, '加拿大', 'Wiebke von Carolsfeld', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Cherry and Virgin', NULL, '日本', 'Masanao Kawajiri', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'The Glorious Dead', NULL, '美国', 'John Adams, Toby Poser', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Wind Breaker', NULL, '日本', 'Kentaro Hagiwara', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Big Break', NULL, '美国', 'Ian Faria', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'The Mutation', NULL, '韩国', 'Shin Su-won', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'I Love Paris', NULL, '法国', 'Nicky Murphy', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Penny Lane Is Dead', NULL, '澳大利亚', 'Mia''Kate Russell', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Tunnels: Sun in the Dark', NULL, '越南', 'Bui Thac Chuyen', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Nightborn', NULL, '芬兰', 'Hanna Bergholm', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Backstage Madness', NULL, '吉尔吉斯斯坦', 'Amanbek Azhymat', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Nameless', NULL, '日本', 'Hideo Jojo', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Zsazsa Zaturnnah', NULL, '菲律宾', 'Avid Liongoren', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Motherwitch', NULL, '塞浦路斯', 'Minos Papas', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Sekiro: No Defeat', NULL, '日本', 'Kenichi Kutsuna', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Niko', NULL, '法国/韩国', 'Julien Birban Levy', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Born in the Jungle', NULL, '拉脱维亚/波兰/捷克', 'Edmunds Jansons', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Teenage Sex and Death at Camp Miasma', NULL, '美国', 'Jane Schoenbrun', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Levitating', NULL, '印度尼西亚', 'Wregas Bhanuteja', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'Trauma or, Monsters All', NULL, '美国', 'Larry Fessenden', NULL, NULL, NULL),
('fantasia', 2026, '第二批片单', 'The Specials', NULL, '日本', 'Eiji Uchida', NULL, NULL, NULL)
on conflict (festival_id,edition,title) do update set section=excluded.section, orig_title=excluded.orig_title, country=excluded.country, director=excluded.director, prize=excluded.prize;
